export const ADMIN_TASKS_REQUEST = 'ADMIN_TASKS_REQUEST'
export const ADMIN_TASKS_SUCCESS = 'ADMIN_TASKS_SUCCESS'
export const ADMIN_TASKS_FAIL = 'ADMIN_TASKS_FAIL'

export const MY_TASKS_REQUEST = 'MY_TASKS_REQUEST'
export const MY_TASKS_SUCCESS = 'MY_TASKS_SUCCESS'
export const MY_TASKS_FAIL = 'MY_TASKS_FAIL'

export const NEW_TASK_REQUEST = 'NEW_TASK_REQUEST'
export const NEW_TASK_SUCCESS = 'NEW_TASK_SUCCESS'
export const NEW_TASK_FAIL = 'NEW_TASK_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const TASK_DETAILS_REQUEST = 'TASK_DETAILS_REQUEST'
export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS'
export const TASK_DETAILS_FAIL = 'TASK_DETAILS_FAIL'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_RESET = 'UPDATE_TASK_RESET'
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_RESET = 'DELETE_TASK_RESET'
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL'